steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/authentication-454507/gcp-api-new', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/authentication-454507/gcp-api-new']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gcp-api-new',
      '--image=gcr.io/authentication-454507/gcp-api-new',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated'
    ]
    
images:
  - gcr.io/authentication-454507/gcp-api-new

options:
  logging: CLOUD_LOGGING_ONLY  
