steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: [
      'compile',
      'com.google.cloud.tools:jib-maven-plugin:3.4.0:build',
      '-Dimage=gcr.io/$PROJECT_ID/gcp-api-new'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gcp-api-new',
      '--image=gcr.io/$PROJECT_ID/gcp-api-new',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
